### ISSUE TITLE
add features 1

### ISSUE THREAD

**Issue by smartsubir** [shyno-org/shyno-org.github.io#1]
1. Add the "Shop" button.
2. Add "add product" and other essential options inside the 'shop' page.

**Comment by smartsubir** [comment]
> 1. Add the "Shop" button.
> 2. Add "add product" and other essential options inside the 'shop' page.

**Comment by smartsubir** [comment]
- [ ] > 1. Add the "Shop" button.
- [ ] > 2. Add "add product" and other essential options inside the 'shop' page.
- [ ] 3. create admin panel. 
4. admin can add a category, product pic, product price, description, and discounts.
5. there will be an option for the customer to write their personal requirements like color, design, etc on the product description page.
6. the list of requirements of the customer has to sent to care@shyno.in

**Comment by krishnapaul242** [comment]
issue created in #2. Issue transfered. Closing this issue.
